apiVersion: v2
name: isto
description: Chart of Charts for istio

type: application
version: 0.1.0
appVersion: "1.16.0"

dependencies:
# helm repo add istio https://istio-release.storage.googleapis.com/charts
- name: istio-base
  version: 1.20.3
  repository: https://istio-release.storage.googleapis.com/charts
- name: istio-cni
  version: 1.20.3
  repository: https://istio-release.storage.googleapis.com/charts
  condition: istio-cni.enabled
- name: istiod
  version: 1.20.3
  repository: https://istio-release.storage.googleapis.com/charts
