apiVersion: v2
name: istio
description: Chart of Charts for istio

type: application
version: 1.20.3
appVersion: "1.20.3"

dependencies:
# helm repo add istio https://istio-release.storage.googleapis.com/charts
- name: base
  version: 1.20.3
  repository: https://istio-release.storage.googleapis.com/charts
- name: istio-cni
  version: 1.20.3
  repository: https://istio-release.storage.googleapis.com/charts
  condition: cni.enabled
- name: istiod
  version: 1.20.3
  repository: https://istio-release.storage.googleapis.com/charts
