name: Deploy Argo Apps

on:
  push:
    branches: [ "main" ]
    # Publish semver tags as releases.
    #tags: [ 'v*.*.*' ]

jobs:
  build:
    runs-on: k8s-deployments
    container:
      image: bitnami/kubectl:latest
    permissions:
      contents: read
      packages: write
      # This is used to complete the identity challenge
      # with sigstore/fulcio when running outside of PRs.
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create kubeconfig
        run: |
          mkdir ~/.kube
          echo "$RANCHER_KUBECONFIG >> ~/.kube/config
          chmod 600 ~/.kube/config

      - uses: azure/k8s-set-context@v1
        with:
          method: kubeconfig
          kubeconfig: ~/.kube/config
          context: rancher
        id: setcontext

      - uses: azure/k8s-deploy@v4
        with:
          action: deploy
          namespace: argocd
          manifests: |
              applicationsets/istio.yaml
